{
    'name': 'AI Operations: Quality',
    'version': '19.0.1.2.0',
    'category': 'Productivity/AI',
    'summary': 'Quality Intelligence tool pack',
    'author': 'AlShayeb Partners',
    'license': 'OPL-1',
    'depends': ['ai_operations', 'stock', 'mrp',
        'ai_operations_inventory',
        'ai_operations_manufacturing',
        'quality_mrp',],
    'data': ['data/policy_pack.xml'],
    'installable': True,
    'application': False,
}
